"""New Ticket Number modifications By Types

Revision ID: 57a10bfed4c6
Revises: 6548268a957b
Create Date: 2025-04-06 23:23:07.901289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a10bfed4c6'
down_revision: Union[str, None] = '6548268a957b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Quitar FK si es necesario (opcional)
    op.drop_constraint('activities_ticket_number_fkey', 'activities', type_='foreignkey')

    # Cambiar tipo en 'tickets' primero
    op.alter_column('tickets', 'ticket_number',
        existing_type=sa.INTEGER(),
        type_=sa.String(length=100),
        existing_nullable=False)

    # Luego cambiar 'activities'
    op.alter_column('activities', 'ticket_number',
        existing_type=sa.INTEGER(),
        type_=sa.String(length=100),
        existing_nullable=False)

    # Restaurar FK (si la quitaste)
    op.create_foreign_key(
        'activities_ticket_number_fkey',
        source_table='activities',
        referent_table='tickets',
        local_cols=['ticket_number'],
        remote_cols=['ticket_number']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Quitar la FK (si la creaste)
    op.drop_constraint('activities_ticket_number_fkey', 'activities', type_='foreignkey')

    # Volver al tipo INTEGER en orden inverso
    op.alter_column('activities', 'ticket_number',
        existing_type=sa.String(length=100),
        type_=sa.INTEGER(),
        existing_nullable=False)

    op.alter_column('tickets', 'ticket_number',
        existing_type=sa.String(length=100),
        type_=sa.INTEGER(),
        existing_nullable=False)

    # Volver a crear la FK con tipo anterior (opcional)
    op.create_foreign_key(
        'activities_ticket_number_fkey',
        source_table='activities',
        referent_table='tickets',
        local_cols=['ticket_number'],
        remote_cols=['ticket_number']
    )
    # ### end Alembic commands ###
