"""Add position attributes

Revision ID: a14887d330ae
Revises: 16c12ce1d0f1
Create Date: 2025-04-22 21:51:15.135525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14887d330ae'
down_revision: Union[str, None] = '16c12ce1d0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('position_x', sa.Float(), nullable=False))
    op.add_column('tables', sa.Column('position_y', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'position_y')
    op.drop_column('tables', 'position_x')
    # ### end Alembic commands ###
